environment:

  matrix:
    - TARGET_ARCH: x86
      CONDA_NPY: 111
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      DISTUTILS_USE_SDK: 1

    - TARGET_ARCH: x86
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda35
      CONDA_PY: 35

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
      CONDA_PY: 35

    - TARGET_ARCH: x86
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36
      CONDA_PY: 36

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_PY: 36

platform:
  - x64

os: Previous Visual Studio 2015
# os: Visual Studio 2013

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"


install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda info
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda
  - cmd: conda install -q --force --no-deps psutil ruamel_yaml requests
  - cmd: conda install -q conda-build=3.0
  - cmd: conda install -q anaconda-client
  - cmd: conda install -q numpy=1.11
  - cmd: pip install twine
  - cmd: pip install pytest
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda info -a && conda list
  - cmd: conda config --add channels landlab
  - cmd: conda install --file=requirements.txt
  - "%WITH_COMPILER% conda build -q -b .conda-recipe"
  - cmd: conda install -q terrainbento --use-local

build: false

test_script:
  - cmd: pytest
