environment:
  TWINE_PASSWORD:
    secure: 7/AZVv0ovctfsb6fBFuC84eyDbvrPSwFlwtIR5RKvQ0=
  matrix:

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python38-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python37-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python36-x64"

platform:
  - x64

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -VV"
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install numpy
  - cmd: pip install statsmodels
  - cmd: pip install landlab --pre
  - cmd: pip install twine pytest pytest-cov pytest-datadir
  - cmd: conda info
  - cmd: conda list

build: false

test_script:
  - pip install -e .
  - pytest -vvv

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'
