name: terrainbento-dev
 channels:
   - conda-forge
 dependencies:
 - python
 - black
 - flake8
 - isort
 - pytest
 - pytest-cov
 - scipy
 - numpy
 - xarray
 - dask
 - landlab>2.0
 - jupyter
 - holoviews
 - pandas
 - dask[complete]
